version: '3.8'

services:

  api:
    build: ./api
    ports:
      - "5050:5050"
    volumes:
      - ./api:/app
    restart: always
    env_file:
      - .env
    command: /start-reload.sh 

  telegram:
    build: ./telegram_bot
    depends_on:
      - api
    env_file:
      - .env